// Constants and configuration values
const DEFAULT_MAX_RESULT_SIZE_GB = 30;

const ADMIN_CONFIG_KEYS = [
  'ADDON_BASE_URL',
  'ADDON_SHARED_SECRET',
  'INDEXER_MANAGER',
  'INDEXER_MANAGER_URL',
  'INDEXER_MANAGER_API_KEY',
  'INDEXER_MANAGER_INDEXERS',
  'INDEXER_MANAGER_STRICT_ID_MATCH',
  'NZBDAV_URL',
  'NZBDAV_API_KEY',
  'NZBDAV_WEBDAV_URL',
  'NZBDAV_WEBDAV_USER',
  'NZBDAV_WEBDAV_PASS',
  'NZBDAV_CATEGORY',
  'NZBDAV_CATEGORY_MOVIES',
  'NZBDAV_CATEGORY_SERIES',
  'NZBDAV_CATEGORY_DEFAULT',
  'NZBDAV_HISTORY_FETCH_LIMIT',
  'NZBDAV_CACHE_TTL_MINUTES',
  'NZB_SORT_MODE',
  'NZB_PREFERRED_LANGUAGE',
  'NZB_MAX_RESULT_SIZE_GB',
  'NZB_TRIAGE_ENABLED',
  'NZB_TRIAGE_MAX_CANDIDATES',
  'NZB_TRIAGE_NNTP_HOST',
  'NZB_TRIAGE_NNTP_PORT',
  'NZB_TRIAGE_NNTP_USER',
  'NZB_TRIAGE_NNTP_PASS',
  'NZB_TRIAGE_NNTP_USE_TLS',
  'NZB_TRIAGE_NNTP_TIMEOUT',
  'NZB_TRIAGE_NNTP_MAX_CONNECTIONS',
  'NZB_TRIAGE_REUSE_POOL',
  'NZB_TRIAGE_NNTP_KEEP_ALIVE_MS',
  'NZB_TRIAGE_PREFETCH_FIRST_VERIFIED',
  'NZB_TRIAGE_ARCHIVE_DIRS',
  'NZB_TRIAGE_MAX_PARALLEL',
  'NZB_TRIAGE_STAT_SAMPLE_COUNT',
  'NZB_TRIAGE_ARCHIVE_SAMPLE_COUNT',
  'NZB_TRIAGE_TIMEOUT_MS',
  'STREAM_CACHE_TTL_MINUTES',
  'STREAM_CACHE_MAX_SIZE_MB',
  'VERIFIED_NZB_CACHE_TTL_MINUTES',
  'VERIFIED_NZB_CACHE_MAX_SIZE_MB',
  'SPECIAL_API_ENABLED',
  'SPECIAL_API_PROVIDER',
  'SPECIAL_API_KEY',
  'TMDB_API_KEY',
  'TMDB_SEARCH_LANGUAGES',
  'TMDB_SEARCH_MODE',
];

const VIDEO_EXTENSIONS = new Set([
  '.mp4', '.mkv', '.avi', '.mov', '.wmv', '.flv',
  '.webm', '.m4v', '.mpg', '.mpeg', '.3gp', '.ts', '.m2ts', '.mts'
]);

module.exports = {
  DEFAULT_MAX_RESULT_SIZE_GB,
  ADMIN_CONFIG_KEYS,
  VIDEO_EXTENSIONS,
};
